// <auto-generated />
using System;
using Conge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Conge.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Conge.Domain.Entities.Anciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<float>("JourIncrimente")
                        .HasColumnType("real");

                    b.Property<int>("PlanDroitCongeID")
                        .HasColumnType("int");

                    b.Property<long>("ToAnc")
                        .HasColumnType("bigint");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanDroitCongeID");

                    b.ToTable("anciente");
                });

            modelBuilder.Entity("Conge.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplementAdresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FiscalNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeRegister")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("Conge.Domain.Entities.Delegation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int>("IdRemplacant")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TitreId")
                        .HasColumnType("int");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TitreId");

                    b.ToTable("delegation");
                });

            modelBuilder.Entity("Conge.Domain.Entities.DemandeConge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebutConge")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRepriseConge")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int>("IdRemplacant")
                        .HasColumnType("int");

                    b.Property<bool>("IsApremDebut")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApremRetour")
                        .HasColumnType("bit");

                    b.Property<float>("NbrBonification")
                        .HasColumnType("real");

                    b.Property<float>("NbrConge")
                        .HasColumnType("real");

                    b.Property<string>("NumeroDemande")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Solde")
                        .HasColumnType("real");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TypeCongeID")
                        .HasColumnType("int");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeCongeID");

                    b.ToTable("demandeConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.Details_DroitConge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<float>("Droit")
                        .HasColumnType("real");

                    b.Property<int>("DroitCongeId")
                        .HasColumnType("int");

                    b.Property<float>("DroitMisAJour")
                        .HasColumnType("real");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DroitCongeId");

                    b.ToTable("details_DroitConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.DocumentsConge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DemandeCongeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemandeCongeId");

                    b.ToTable("documentsConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.DroitConge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MoisAffectation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("droitConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConsultantExterne")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDateCin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Langue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPersonne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceCin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanDroitCongeIDConsumed")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecruitementDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RegimeTravailID")
                        .HasColumnType("int");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelGSM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TitularizationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidityDateRP")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("Conge.Domain.Entities.JoursFeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("jour")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("joursFeries");
                });

            modelBuilder.Entity("Conge.Domain.Entities.MvtConge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<float>("NbreJours")
                        .HasColumnType("real");

                    b.Property<int>("Sens")
                        .HasColumnType("int");

                    b.Property<float>("SoldeApres")
                        .HasColumnType("real");

                    b.Property<int>("TypeCongeID")
                        .HasColumnType("int");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeCongeID");

                    b.ToTable("mvtConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.PlanDroitConge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("planDroitConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.Seuils", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<float>("Seuil")
                        .HasColumnType("real");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Valeur")
                        .HasColumnType("real");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("seuils");
                });

            modelBuilder.Entity("Conge.Domain.Entities.SoldeConge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<float>("Solde")
                        .HasColumnType("real");

                    b.Property<int>("TypeCongeID")
                        .HasColumnType("int");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeCongeID");

                    b.ToTable("soldeConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.TitreConge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebutConge")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRepriseConge")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelegationId")
                        .HasColumnType("int");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int>("IdRemplacant")
                        .HasColumnType("int");

                    b.Property<bool>("IsApremDebut")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApremRetour")
                        .HasColumnType("bit");

                    b.Property<float>("NbrBonification")
                        .HasColumnType("real");

                    b.Property<float>("NbrConge")
                        .HasColumnType("real");

                    b.Property<string>("NumeroDemande")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTitre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TypeCongeID")
                        .HasColumnType("int");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DelegationId");

                    b.HasIndex("TypeCongeID");

                    b.ToTable("titreConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.TypeConge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CongeAnnuel")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModif")
                        .HasColumnType("datetime2");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemplacement")
                        .HasColumnType("bit");

                    b.Property<int?>("NombreFois")
                        .HasColumnType("int");

                    b.Property<float?>("NombreJours")
                        .HasColumnType("real");

                    b.Property<int?>("Period")
                        .HasColumnType("int");

                    b.Property<string>("UserCreat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.Property<string>("messageNotification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("notification")
                        .HasColumnType("bit");

                    b.Property<bool>("soldeNegatif")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("typeConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.Anciente", b =>
                {
                    b.HasOne("Conge.Domain.Entities.PlanDroitConge", "PlanDroitConge")
                        .WithMany("Anciente")
                        .HasForeignKey("PlanDroitCongeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanDroitConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.Delegation", b =>
                {
                    b.HasOne("Conge.Domain.Entities.TitreConge", "Titre")
                        .WithMany()
                        .HasForeignKey("TitreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Titre");
                });

            modelBuilder.Entity("Conge.Domain.Entities.DemandeConge", b =>
                {
                    b.HasOne("Conge.Domain.Entities.TypeConge", "TypeConge")
                        .WithMany("DemandeConge")
                        .HasForeignKey("TypeCongeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.Details_DroitConge", b =>
                {
                    b.HasOne("Conge.Domain.Entities.DroitConge", "DroitConge")
                        .WithMany("Details_DroitConge")
                        .HasForeignKey("DroitCongeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DroitConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.DocumentsConge", b =>
                {
                    b.HasOne("Conge.Domain.Entities.DemandeConge", "DemandeConge")
                        .WithMany()
                        .HasForeignKey("DemandeCongeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.MvtConge", b =>
                {
                    b.HasOne("Conge.Domain.Entities.TypeConge", "TypeConge")
                        .WithMany("MvtConge")
                        .HasForeignKey("TypeCongeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.SoldeConge", b =>
                {
                    b.HasOne("Conge.Domain.Entities.TypeConge", "TypeConge")
                        .WithMany("SoldeConge")
                        .HasForeignKey("TypeCongeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.TitreConge", b =>
                {
                    b.HasOne("Conge.Domain.Entities.Delegation", "Delegation")
                        .WithMany()
                        .HasForeignKey("DelegationId");

                    b.HasOne("Conge.Domain.Entities.TypeConge", "TypeConge")
                        .WithMany("TitreConge")
                        .HasForeignKey("TypeCongeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delegation");

                    b.Navigation("TypeConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.DroitConge", b =>
                {
                    b.Navigation("Details_DroitConge");
                });

            modelBuilder.Entity("Conge.Domain.Entities.PlanDroitConge", b =>
                {
                    b.Navigation("Anciente");
                });

            modelBuilder.Entity("Conge.Domain.Entities.TypeConge", b =>
                {
                    b.Navigation("DemandeConge");

                    b.Navigation("MvtConge");

                    b.Navigation("SoldeConge");

                    b.Navigation("TitreConge");
                });
#pragma warning restore 612, 618
        }
    }
}
